name: ViT-H-14
img_size: ${dataset.img_size}
patch_size: 14
img_chls: ${dataset.img_chls}
n_class: ${dataset.n_class}
n_layer: 32
n_heads: 16
n_embd: 1280
mlp_dim: 5120
drop_rate: 0.1
attn_drop_rate: 0.1
stoch_depth_drop_rate: 0.2